query getAllProducts {
  products(first: 18) {
    edges {
      node {
        id
        title
        handle
        priceRange {
          minVariantPrice {
            amount
            currencyCode
          }
          maxVariantPrice {
            amount
            currencyCode
          }
        }
        images(first: 1) {
          edges {
            node {
              transformedSrc(maxWidth: 600)
            }
          }
        }
      }
    }
  }
}
